services:
  - type: web
    name: shein-bot
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y chromium chromium-driver
      pip install -r requirements.txt
    startCommand: python my.py
